export const ISOCodeList = [
	"ar",
	// "bn",
	"de",
	"en",
	// "es",
	// "fr",
	// "hi",
	"jp",
	// "ko",
	// "ms",
	// "pt",
	// "ru",
	// "tr",
	// "ur",
	// "vi",
	"zh"
];

// source: https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
export const Endonyms = {
	ar: "العربية",
	bn: "বাংলা",
	de: "Deutsch",
	en: "English",
	es: "Español",
	fr: "Français",
	hi: "हिन्दी",
	jp: "日本語",
	ko: "한국어",
	ms: "Bahasa Melayu",
	pt: "Português",
	ru: "Русский",
	tr: "Türkçe",
	ur: "اردو",
	vi: "Việtnam",
	zh: "中文",
};

export const EndonymToCode = {
	"العربية": "ar",
	"বাংলা": "bn",
	"Deutsch": "de",
	"English": "en",
	"Español": "es",
	"Français": "fr",
	"हिन्दी": "hi",
	"日本語": "jp",
	"한국어": "ko",
	"Bahasa Melayu": "ms",
	"Português": "pt",
	"Русский": "ru",
	"Türkçe": "tr",
	"اردو": "ur",
	"Việtnam": "vi",
	"中文": "zh",
};
